- hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Gather all instances
    amazon.aws.ec2_instance_facts:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
    register: result
  - name: Print Instances
    debug:
      msg: "{{ item.instance_id }}"
    with_items:
      - "{{ result.instances }}"

